@node
@author=Jozef Israels
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@contributors2=Leo Jansen, Peter Boot, Beatrice Nava, Mariken Teeuwen
@contributors3="N.N."
@conversionCode=tei
@conversionMethod=literal
@converter=Dirk Roorda (Text-Fabric)
@description=this is TEI attribute status
@descriptionTf=Critical edition
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@institute3=VGM (Van Gogh Museum) Amsterdam
@language=nl
@schema=TEI + editem-about + editem-letter + editem-artworklist + editem-biolist + editem-bibliolist
@sourceFormat=TEI
@teiVersion=2025-07-09
@title=Letters
@valueType=str
@version=0.3.0
@writtenBy=Text-Fabric
@dateWritten=2025-08-05T09:39:36+00:00Z

118396	restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
unknown
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
restricted
